# .streamlit/secrets.toml

[dataforseo]
login = "sulik@birne.sk"
password = "8867a612eb1cb71d"

[app]
pin = "1337" # PIN pre druhú požiadavku

[supabase]
url = "https://fymqvozezdwygpbwglae.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5bXF2b3plemR3eWdwYndnbGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODY0MDksImV4cCI6MjA2Mzg2MjQwOX0.s71x0CNHxIt97sNnaeGIMwAjdAadxyra6v42iRdow70"
db_url = "postgresql://postgres:xigjos-ropfY6-fukrus@db.fymqvozezdwygpbwglae.supabase.co:5432/postgres"